### ISSUE TITLE
Send story ?

### ISSUE THREAD

**Issue by waveur35** [liamcottle/Snapchat-SDK-PHP#1]
Hello,

I'm a pretty noob in all of this, but I just want to know if actually, your code can send story or not ? Sorry for my easy question

Thanks for your hardwork and I hope you will find out a way to send story :)

**Comment by liamcottle** [comment]
Hey @waveur35

Stories (and Snaps) can be uploaded and sent using the `uploadPhoto` / `uploadVideo` methods, along with the `sendMedia` method.

Here's an example.

```
//Upload Photo to Snapchat
$uploadPayload = $snapchat->uploadPhoto("photo.jpg");

//Send as Story (empty array is no recipients) (true means set as story)
$snapchat->sendMedia($uploadPayload, 10, array(), true);
```

If you need more info about a method in the `Snapchat` class, take a look at the Doc Blocks :)

**Comment by waveur35** [comment]
Amazing ! Thank you a lot I will try this today !! :)

**Comment by waveur35** [comment]
I'm getting this error (I want to try my script before buying your API key)

"Snapchat Request failed: [POST] [https://app.snapchat.com/loq/login] SSL certificate problem: unable to get local issuer certificate"

**Comment by waveur35** [comment]
Solved !
