### ISSUE TITLE
It shows me this error :(

### ISSUE THREAD

**Issue by kripsbro** [liamcottle/Snapchat-SDK-PHP#10]
Casper API Response: [/snapchat/ios/login] [401] JWT Token has Expired

**Comment by liamcottle** [comment]
Hiya,

Please make sure the time settings on your server are correct. JWT tokens generated in the SDK are valid for 60 seconds.

If the time on your server is out (eg, by 60 seconds), the tokens will already be invalid when you make your API request.

If you aren't able to correct the time settings on your server, let me know.

Thanks
