### ISSUE TITLE
Error: Project does not have access to Snapchat Endpoint: /bq/blob' when trying to download snap

### ISSUE THREAD

**Issue by ramseydsilva** [liamcottle/Snapchat-SDK-PHP#11]
There is not much information on this. Any help is appreciated. My code very much resembles the example: https://github.com/liamcottle/Snapchat-SDK-PHP/blob/master/examples/example.loginAndDownloadUnviewedSnaps.php. The error is thrown at line: `$snapchat->downloadSnap($snap, $filename, $filename_overlay);`

**Comment by liamcottle** [comment]
Hiya,

Sorry for the lack of documentation 🙃 I do plan to set up docs on the Developer Console, I just haven't had the chance...

Simple fix for this, just login to the Developer Console, navigate to the Projects page, and click the 'Edit' icon next to your Project.

From there, you will need to enable all of the Snapchat endpoints that you wish to access via the SDK.

Once saved, this error will disappear :)

**Comment by ramseydsilva** [comment]
Thank you. Been busy, will try soon.
