### ISSUE TITLE
https://developers.casper.io/ is DOWN. 

### ISSUE THREAD

**Issue by waveur35** [liamcottle/Snapchat-SDK-PHP#12]
The error "Operation timed out after 10000 milliseconds with 0 bytes received".

Everything is in the title. I use this API for a while (1 month) but now the website is down, and when I try to send snap I've this error "Operation timed out after 10000 milliseconds with 0 bytes received".

Hope you will fix it soon Liam.

**Comment by Chiggins** [comment]
https://www.facebook.com/casper4snapchat/posts/1674487176150870

**Comment by waveur35** [comment]
Oh thank you, I'm not on the facebook page

**Comment by liamcottle** [comment]
Sorry for the delay in response. This has now been resolved, however I'm still monitoring everything closely.
