### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kripsbro** [liamcottle/Snapchat-SDK-PHP#13]
Snapchat Request failed: [POST] [https://app.snapchat.com/loq/login] HTTP/1.1 403 Forbidden

**Comment by liamcottle** [comment]
Hiya, This has now been resolved. Sorry for the inconvenience.

**Comment by kripsbro** [comment]
again it shows  Snapchat Request failed: [POST] [https:\/\/app.snapchat.com\/loq\/login] HTTP\/1.1 403 Forbidden
