### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by kripsbro** [liamcottle/Snapchat-SDK-PHP#14]
Snapchat Request failed: [POST] [https:\/\/app.snapchat.com\/loq\/login] HTTP\/1.1 403 Forbidden

**Comment by liamcottle** [comment]
Sorry, I misread your [previous issue](https://github.com/liamcottle/Snapchat-SDK-PHP/issues/13) and thought it was the Casper server having the issues.

I've tested the login on multiple servers and multiple accounts.

It could be possible that your server IP has been blocked by Snapchat.

My suggestion would be to try using proxies, or another server/IP.

**Comment by kripsbro** [comment]
How i can use proxies with this api?

**Comment by liamcottle** [comment]
An example can be seen [here](https://github.com/liamcottle/Snapchat-SDK-PHP/blob/master/examples/example.other.php#L12)
