### ISSUE TITLE
Error when uploading media

### ISSUE THREAD

**Issue by kripsbro** [liamcottle/Snapchat-SDK-PHP#15]
Operation timed out after 10001 milliseconds with 0 bytes received

**Comment by stc-1** [comment]
Can i take a new filter of you pleas . NAME OF FILTER IS GOOLD . PLEAS SEND TO MY E MILE AND ADD DAWNLOED IN THIS E MAIL. THANK YOU

**Comment by liamcottle** [comment]
It's likely the server was down, or the file was taking too long to upload.
