### ISSUE TITLE
Hello can you help me please

### ISSUE THREAD

**Issue by kripsbro** [liamcottle/Snapchat-SDK-PHP#18]
{"SUCCES":"Snapchat Request failed: [POST] [https:\/\/app.snapchat.com\/loq\/login] HTTP\/1.1 403 Forbidden"}

**Comment by liamcottle** [comment]
Hi, your IP address has been banned by Snapchat.

**Comment by kripsbro** [comment]
how i can made an app without get banned by SnapChat ? if i will use objective-c kit it will work ?

**Comment by liamcottle** [comment]
The best way to avoid IP bans, is to only use one or two accounts per IP address, and if you have a lot of accounts, make the Snapchat API requests on the client device rather than your server.
