### ISSUE TITLE
will the account be locked using the api ?

### ISSUE THREAD

**Issue by mzahlag** [liamcottle/Snapchat-SDK-PHP#19]
Dear Liam

Since the locking accounts spread out i didn't use the api my subscription still active though, But I'm worried that my account will be locked if i use the Casper Api any info about it how to workaround it ? It would be helpful for all of the developers who is using your Api

Regards

**Comment by liamcottle** [comment]
Hiya,

Unfortunately at this stage, I don't have a way around the account locks.

However, I have only been locked once, on one of my many testing accounts, which makes it difficult to figure out what causes them.

I am still looking into this though.
