### ISSUE TITLE
Payment issus

### ISSUE THREAD

**Issue by waveur35** [liamcottle/Snapchat-SDK-PHP#2]
Hello,

I've actually an "[/bq/post_story] [202] Request Failed!" error.

So I was thinking that's because I need a subscription. But when I try to pay for 100$ with paypal, I got this error : http://puu.sh/n4How/5eac1a38da.png

=> Param A3, P3 and T3 are incorrect, idk what does that mean.

So you just can tell me how to subscribe and/or how to solve the "[/bq/post_story] [202] Request Failed!" error ?

Thank you. :) My account email start with "wavew.....@gm....com"

**Comment by liamcottle** [comment]
Hi @waveur35 

I'm not sure why you're getting '202', however the Subscription button has been fixed and you should be able to make a purchase now.

Sorry for the inconvenience.

**Comment by waveur35** [comment]
Okey thank you ! I will purchase it in few hour.
