### ISSUE TITLE
General LOGIN issues

### ISSUE THREAD

**Issue by waveur35** [liamcottle/Snapchat-SDK-PHP#23]
Hello,

I use the API for 3 month now, everything works fine, but actually I'm not able to login and post story anymore.

Look the error : http://puu.sh/oZ9ry/58ed36e7a1.png

I just want to know what's going on please :)

Regards

**Comment by liamcottle** [comment]
Hi @waveur35,

I've had a few issues with my backend systems over the last couple of days.

Everything should be working as expected now.

I'm still monitoring it all, to make sure it runs as expected.

Cheers.
