### ISSUE TITLE
How to use LogoutRequest.

### ISSUE THREAD

**Issue by mzaboss** [liamcottle/Snapchat-SDK-PHP#25]
I just wonder, how to use LogoutRequest?, It's not in Snapchat.php, Kindly can you upload an example in examples folder. 

Thank you in advance.

**Comment by liamcottle** [comment]
Hi, as of latest commit this can be done by calling the `logout` method on the Snapchat instance.

Commits:
- 7f62ee855fa4b7f0042f16d9fb559ab1d0dfa09f
- 1cf70a1087c1579c4afde76ee15b84f05b686b26
