### ISSUE TITLE
Register API endpoint

### ISSUE THREAD

**Issue by EthanSbbn** [liamcottle/Snapchat-SDK-PHP#3]
Hi Liam,

Is the "register" API endpoint something your API will expose some day ?
Have a project in mind, and would love to purchase you a subscription, but being able to register programmatically is required for us.

Thanks

**Comment by liamcottle** [comment]
Hi @EthanSbbn,

Yes I do plan to add registration methods to this project, however you will still need human interaction during the registration process as there will be a Snapchat Captcha to complete.

More info will be posted about this, once I've gotten I add it to the SDK.

**Comment by liamcottle** [comment]
As of the latest commit, Registration is now supported. An example command line tool can be found in the example folder.
