### ISSUE TITLE
Casper on Bluestacks!

### ISSUE THREAD

**Issue by rsflow** [liamcottle/Snapchat-SDK-PHP#33]
Hey @liamcottle ,

I have installed Casper on Bluestacks on Windows but every time I open the side drawer menu shows different items and never all of them. 
I have reinstalled Bluestacks and Casper many times but still the same issue.

![screen shot 2016-07-22 at 9 13 12 pm](https://cloud.githubusercontent.com/assets/6751025/17068633/5ad02a02-5052-11e6-842e-456f751aeb76.png)

Thank You for your help!

**Comment by liamcottle** [comment]
This is not the place to post Casper issues. However, I have had reports of that happening in emulators. Unfortunately I don't know what causes it. Try using a real device.

**Comment by rsflow** [comment]
Thank you and sorry about that  :)
