### ISSUE TITLE
API down?

### ISSUE THREAD

**Issue by mzaboss** [liamcottle/Snapchat-SDK-PHP#35]
Timeout response from (https://casper-api.herokuapp.com/snapchat/ios/login)

Operation timed out after 30000 milliseconds with 0 bytes received

```
<!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
```
Please advice.

**Comment by mzaboss** [comment]
Never mind, It works now.

**Comment by mzaboss** [comment]
Back down again for some reason. OP, kindly update.

**Comment by liamcottle** [comment]
There's a city wide power outage which is likely to be for the next few
hours. Sorry for any inconvenience but I can't do anything about this.

**Comment by liamcottle** [comment]
The downtime earlier was also caused by another power outage which lasted a
couple of hours.

**Comment by mzaboss** [comment]
No worries buddy, keep the good work, thank you for your update, cheers.

**Comment by mzaboss** [comment]
Works again, thank you.
