### ISSUE TITLE
You're using a version of Snapchat or operating system that's no longer supported.

### ISSUE THREAD

**Issue by waveur35** [liamcottle/Snapchat-SDK-PHP#38]
Hello,

I'm getting this error for now two day on 50% of my account : 

```
You're using a version of Snapchat or operating system that's no longer supported. Please upgrade your device's operating system and update to the newest app version to use Snapchat. Thanks!

Fatal error: Call to a member function getUsername() on null in C:\inetpub\wwwroot\src\Snapchat.php on line 201
```

I've myself put this line of code at the line 200 of Snapchat.php to see the error:

```
echo $response->getMessage().'</br>';
$this->cached_updates_response = $response->getUpdatesResponse();
```

Is there any way to fix it ? Anyone having this issus?

Regards.

**Comment by JordanWoods** [comment]
I am getting this same error, tried on 3 different emulators and 2 devices all with the same account. I will make a new account and see if it happens with that also.

**Comment by waveur35** [comment]
Any idea of why this error happen suddendly ?

**Comment by JordanWoods** [comment]
No idea, although the account that it kept happening to me on was temporarily locked by snapchat several times.  I don't know if it is maybe something within the snapchat database/server that is blocking certain accounts from connecting.

**Comment by xopyip** [comment]
In LoginRequest.php line 63 add this:
$login["headers"]["User-Agent"] = "Snapchat/9.35.5.0 (iPod7,1; iOS 8.4; gzip)";
It working for me.

**Comment by liamcottle** [comment]
Snapchat tokens contain the iOS and App version in them, so changing the User Agent might work as a work around, but it's an instant flag for an account lock.

However, I do believe I fixed this issue a short time after you'd posted this, but forgot to comment/close it 😆
