### ISSUE TITLE
Getting failed request - Login

### ISSUE THREAD

**Issue by peterlevin** [liamcottle/Snapchat-SDK-PHP#4]
Snapchat Request failed. 403 Forbidden

when trying to login.

**Comment by liamcottle** [comment]
Hi Peter,

I've downloaded a fresh copy of the SDK directly from GitHub and tested your API credentials with a test Snapchat account I have, and I'm able to login and fetch stories etc...

Could you post the code that you're using, so I can look into this for you? Minus your credentials of course.

Please note, (I'll need to add this to the readme), you'll need to have the mcrypt extension installed in PHP.

Cheers.

**Comment by peterlevin** [comment]
Thanks for prompt response. I installed mcrypt and same error. Any other dependencies? Here is the code:

require("./src/autoload.php");
$casper = new \Casper\Developer\CasperDeveloperAPI("", "");
$snapchat = new \Snapchat\Snapchat($casper);

try {

    $login = $snapchat->login("", "");
	
	
} catch(Exception $e){
    echo $e->getMessage() . "\n";
}

**Comment by waveur35** [comment]
Hello,

I'm pretty sure it's just an IP ban error. I'm getting this error when I don't use my proxy. Snapchat have ban 99% of proxy IP, try sslprivateproxy, they sale really good one for snapchat

Greetz

**Comment by liamcottle** [comment]
This above comment by @waveur35 sounds like the most likely reason you're getting a 403 on Login.

I've tested multiple accounts on different servers and I'm able to login.

If you're not using a proxy, then it's most likely the server you're running on has it's IP banned or even blacklisted.

This library supports setting a proxy to use for Snapchat API requests, by calling `setProxy($proxy)` on the Snapchat instance.

Let me know if this solves the issue :)

**Comment by peterlevin** [comment]
Got it working on a different server. Thanks guys.

**Comment by liamcottle** [comment]
Great to hear!
