### ISSUE TITLE
My links in chat are not clickable - what's the forrect format

### ISSUE THREAD

**Issue by klliks-com** [liamcottle/Snapchat-SDK-PHP#43]
Hello.

When sending message between users my ckick arrived to other side, but they are not clickable.

While on real device they are clickable.
What im doing wrong? Should i send links in soecific format?

Thanks

**Comment by liamcottle** [comment]
This library doesn't support sending chat messages at this time. It may do in the future though.

**Comment by klliks-com** [comment]
Ok. But lets say i succeed. Can u tell me what should i do fir links be clickable?

Thanks

**Comment by klliks-com** [comment]
@liamcottle
