### ISSUE TITLE
error 500 when trying to view story

### ISSUE THREAD

**Issue by klliks-com** [liamcottle/Snapchat-SDK-PHP#44]
Hello.

What us the meaning of thus error? Im trying ti view stories without success, is there documentation for this one.

Also when trying ti search for users i get kimit of 100 search per account. Any idea how long this limit? Can u share documentation on all sc limitation?

Thanks

**Comment by klliks-com** [comment]
Anyone?

**Comment by liamcottle** [comment]
I don't have any documentation on this, however if you research this yourself please feel free to post your findings here. I've tested this library for downloading stories today, and it worked as expected.

The 500 Internal Server error you received was likely a temporary issue, and trying again later will probably work.

**Comment by klliks-com** [comment]
Download story is succeed but how can i actualky make the system mark them
as "viewed by user"

בתאריך 14 באוק' 2016 17:00,‏ "Liam Cottle" <notifications@github.com> כתב:

**Comment by mzaboss** [comment]
`					sleep(SLEEP_TIME);
					$storiesResponse = $login->getStoriesResponse();
				foreach($storiesResponse->getFriendStories() as $friendStories){
					if($friendStories->getUsername() == "mzaboss"){ 
						echo "debugger - mzaboss found!\n";
					$friendStoriesUsername = $friendStories->getUsername();
						$storiesContainer = $friendStories->getStories();    
					foreach($storiesContainer as $storyContainer){
					$story = $storyContainer->getStory();
					echo "Mark as viewed story ID: " . $story->getId() . "\n";
						$snapchat->markStoryViewed($story->getId());
					}`

**Comment by mzaboss** [comment]
Try this: https://gist.github.com/anonymous/613510338c3a09270c26353481c1eeee#file-marker-as-viewed
