### ISSUE TITLE
Snapchat version no longer supported : API not functionnal anymore

### ISSUE THREAD

**Issue by waveur35** [liamcottle/Snapchat-SDK-PHP#48]
Hello,

I get this error for one day now. Can you update the API or commit a fix ? Thank you. :)

> You're using a version of Snapchat or operating system that's no longer supported. Please upgrade your device's operating system and update to the newest app version to use Snapchat. Thanks!

**Comment by liamcottle** [comment]
Update API - can you confirm this is fixed ?

**Comment by waveur35** [comment]
Yes it's fixed thank you!!
Just to let you know, actually there is this error:

> Snapchat Request failed: [POST] [https://app.snapchat.com/bq/upload] HTTP/1.1 401 Unauthorized
