### ISSUE TITLE
Casper API Response: [/snapchat/ios/login] [401] API Key is Invalid.

### ISSUE THREAD

**Issue by FFServices** [liamcottle/Snapchat-SDK-PHP#5]
Dear Liam, 

First of all, thank you for your SDK.
When i try to login with the code from the example, I always get this error msg. I've tried to delete my casper project than create a new one (id394), but it is still the same. Can you help me?
Thank you

**Comment by liamcottle** [comment]
Hiya, You will need to register on the new [Casper Developers](https://developers.casper.io) website, and submit your Project for review.

**Comment by FFServices** [comment]
Thanks for your fast answer :)
registered, id #81

**Comment by LanchaBasualdo** [comment]
@liamcottle do you need help with joining the snap and the overlay? I have and old function created for the mgp25/SC-API which could help

**Comment by liamcottle** [comment]
Hi @LanchaBasualdo,

I'd be keen to add that in, however have it as an optional method.

This way, for those that don't want the Caption/Drawing overlay on the videos, can still have it like so.

**Comment by LanchaBasualdo** [comment]
@liamcottle 
This is the quick dirty code I used to use. I'm not willing to pay for the subscription so I could not try it.
But here I leave it to you if you want to adapt it.
https://www.dropbox.com/s/qoqyu6cbekdjor4/Overlay.php?dl=0

**Comment by liamcottle** [comment]
Cheers, I'll take a look into this and get it implemented.

**Comment by tushar66** [comment]
Hi @liamcottle 

I am trying to get registered on your website for getting API key, but it is showing "New registrations are not being accepted at this time.".

**Comment by rpcarnell** [comment]
I am having the same problem. What's going with their website?

**Comment by liamcottle** [comment]
That's because:
>New registrations are not being accepted at this time.

**Comment by Himnshu** [comment]
Hi @liamcottle 
When it will be accepted the new registrations. it will be accepted in future or not?
