### ISSUE TITLE
Story method

### ISSUE THREAD

**Issue by sekouperry** [liamcottle/Snapchat-SDK-PHP#6]
Hello.
I know there is a method for getStories.
Is there a method in your api for setStories, so I will be able to send.
I would like my app to be able to send snaps to friends and added to stories.

**Comment by liamcottle** [comment]
Hey @sekouperry,

Stories are sent with the same function as Snaps.

Here's the example to send Snaps: [example.loginAndSendSnap.php](https://github.com/liamcottle/Snapchat-SDK-PHP/blob/master/examples/example.loginAndSendSnap.php)

To send the snap as a story only, you will need to change the `sendMedia` parameters from:
```
$snapchat->sendMedia($uploadPayload, 10, array("recipient"));
```
To:
```
$snapchat->sendMedia($uploadPayload, 10, array(), true);
```

The empty array, means you don't want to send it to any usernames, and the `true` boolean will set it as your story.

Of course, you can also send the snap to friends as well as setting it as the story.
