### ISSUE TITLE
SnapChat Upload

### ISSUE THREAD

**Issue by kripsbro** [liamcottle/Snapchat-SDK-PHP#8]
Snapchat Request failed: [POST] [https://app.snapchat.com/bq/upload] HTTP/1.1 413 Request Entity Too Large"

**Comment by kripsbro** [comment]
I resized Image up to 2mb and now it showing "Snapchat Request failed: [POST] [https://app.snapchat.com/loq/send] HTTP/1.1 400 Bad Request"

**Comment by liamcottle** [comment]
Hiya,

Generally you'll want to make sure the image is ~200kb, as that's the approximate size sent in the official app.

Setting the JPEG quality to 60%, will decrease the file size greatly, and still keep high quality.

Unfortunately I'm not sure what's causing the `400 Bad Request`

**Comment by kripsbro** [comment]
Can you check ?

**Comment by liamcottle** [comment]
Hiya,

I have downloaded a fresh copy of the SDK and tested the sending of photos.

Unfortunately I am unable to replicate the `400 Bad Request` that you are receiving.

... are you still having this issue?

**Comment by kripsbro** [comment]
No , resolvet thanks :)
